### ISSUE TITLE
Jumpy on text input (Firefox on Android)

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#242] opened 2023-03-02 21:07 UTC
The start page is kind of jumpy in Firefox for Android when the search field gets focus. In Chrome it's fine.

https://user-images.githubusercontent.com/8180537/222553043-90a5301d-9d54-45e0-9feb-77f84e2e5a41.mp4

**Comment by phylor** [comment] 2023-03-02 21:32
Cannot reproduce on my Android with Firefox.

It seems to zoom the whole page a bit.

@cabotine The search field should already have the focus when the page loads. Is that not the case for you?

**Comment by cabotine** [comment] 2023-03-03 18:23
No it is not.
Checked also with different versions of Firefox (and Firefox Beta).

https://user-images.githubusercontent.com/8180537/222797968-df398b41-32b0-45e5-96a5-5b0b9330a370.mp4

![Screenshot_20230303-161214](https://user-images.githubusercontent.com/8180537/222798087-adc9c58a-8d81-4084-a70d-cb5763d0d5fa.png)
![Screenshot_20230303-104618](https://user-images.githubusercontent.com/8180537/222798091-e308d82b-cb33-4447-a152-94d1b7a9ffc0.png)

**Comment by phylor** [comment] 2023-03-06 20:37
I have the same stable Firefox version and unfortunately still can't reproduce the focus issue.

There is some strange zoom behavior though (when zooming in I can't zoom out completely anymore, unless the search results are shown). I don't think that fixing that would fix the focus issue, but it would certainly improve the behavior.


https://user-images.githubusercontent.com/1394828/223224839-d2a0dce3-b2fc-47d0-b99d-c394baae821f.mp4

**Comment by wintermeyer** [comment] 2023-03-07 06:19
I close this issue. I don't want this to become a rabbit whole. At least for now. In case this is a problem for other people too it will pop up again.

@cabotine Please add the kind of device and the OS and Browser version to this issue in case we need it as a reference in the future.

**Closed by wintermeyer** 2023-03-07 06:19 UTC
