### ISSUE TITLE
Sorting search results

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#212] opened 2023-02-27 20:11 UTC
Search results currently have a problem if the word starts with a letter at the end of the alphabet because the results are ordered alphabetically.
For pupils this is frustrating as they expect to have the word they typed at the beginning of the list.
We thought we might solve this sorting issue by turning of the phonetic search for the moment but, at the end the same happens with the regular search :(

![grafik](https://user-images.githubusercontent.com/8180537/221672449-2acc5d5a-71d2-4465-8965-ad53c963eb91.png)

**Comment by wintermeyer** [comment] 2023-02-27 21:02
We'll tackle this. Soon. But not today. It is on the roadmap. 

I was aware of this:
https://github.com/wort-schule/wort.schule/issues/170

> Die Funktionalität der Suche und Sortierung solle in einer eigenen Methode abgebildet werden, die später erweitert oder verbessert werden kann.

I close the issue now because it is not a bug. I want to finish other stuff first. Mainly https://github.com/wort-schule/wort.schule/issues/194 and https://github.com/wort-schule/wort.schule/issues?q=is%3Aissue+is%3Aopen+label%3Abug

**Closed by wintermeyer** 2023-02-27 21:02 UTC
